"""update_job_model

Revision ID: 64cbecff7d2a
Revises: 2b17be16921a
Create Date: 2026-01-04 12:51:13.979819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64cbecff7d2a'
down_revision: Union[str, Sequence[str], None] = '2b17be16921a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('location', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('status', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('responsibilities', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('required_skills', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('preferred_skills', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('tools', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('min_qualifications', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'min_qualifications')
    op.drop_column('jobs', 'tools')
    op.drop_column('jobs', 'preferred_skills')
    op.drop_column('jobs', 'required_skills')
    op.drop_column('jobs', 'responsibilities')
    op.drop_column('jobs', 'status')
    op.drop_column('jobs', 'deadline')
    op.drop_column('jobs', 'duration')
    op.drop_column('jobs', 'location')
    # ### end Alembic commands ###
