"""add_student_profile_tables

Revision ID: 6a448a3d8d11
Revises: 3aa242ca9966
Create Date: 2026-01-11 01:06:15.817238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a448a3d8d11'
down_revision: Union[str, Sequence[str], None] = '3aa242ca9966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_student_profiles_id'), 'student_profiles', ['id'], unique=False)
    op.create_table('portfolio_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_projects_id'), 'portfolio_projects', ['id'], unique=False)
    op.create_table('student_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_skills_id'), 'student_skills', ['id'], unique=False)
    op.drop_index(op.f('ix_student_projects_id'), table_name='student_projects')
    op.drop_table('student_projects')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_column('users', 'professional_summary')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'portfolio_url')
    op.drop_column('users', 'github_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('portfolio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('professional_summary', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_table('skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='skilllevel'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('skills_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skills_pkey'))
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('student_projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('tech_stack', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('project_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('student_projects_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_projects_pkey'))
    )
    op.create_index(op.f('ix_student_projects_id'), 'student_projects', ['id'], unique=False)
    op.drop_index(op.f('ix_student_skills_id'), table_name='student_skills')
    op.drop_table('student_skills')
    op.drop_index(op.f('ix_portfolio_projects_id'), table_name='portfolio_projects')
    op.drop_table('portfolio_projects')
    op.drop_index(op.f('ix_student_profiles_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
